# Use a clean base image
FROM node:14

# Set working directory
WORKDIR /app

# Copy the server source code from the host to the container (WORKDIR)
COPY . .

# Install dependencies
RUN npm install

# Makes React’s dev server poll for changes every few milliseconds, which fixes hot reload inside Docker.
ENV CHOKIDAR_USEPOLLING=true

# Start the app
CMD ["npm", "start"]
