services:

  server-dev:
    build:
      context: ./server # path to the server directory in host machine
      dockerfile: Dockerfile.dev
    container_name: server-dev # fixed, predictable name for the container
    ports:
      - 8080:8080  # map port 8080 on the host machine to port 8080 in the container
    volumes:
      - ./server:/app # map the server directory in the host machine to /app in the container
                      # this makes it possible to see changes in the host machine reflected in the container, which triggers nodemon
      - /app/node_modules # this is to prevent overwriting the node_modules directory in the container with the one in the host machine
    env_file:
      - .env

  client-dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client-dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
      
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pick_and_roll
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: