# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the server source code from the host to the container (WORKDIR)
COPY . .

# Install dependencies
RUN npm install

# Expose the backend port
EXPOSE 8080

# run server in development mode
CMD ["npm", "run", "dev"]

